### ISSUE TITLE
Understanding IoC Parser

### ISSUE THREAD

**Issue by lbettels** [SpringJasmine/Jasmine#3]
Hello,
first of all thank you for the tool, once I got everything set up it helped me a lot with my analysis.
I need some help understanding how to utilize the IoC-Analysis.
In the project I analyze, there is an Autowired interface, ```IService```.
That interface is implemented by ```ServiceImpl```.
From the debugger I can see that Jasmine finds the Implementation class and registers it in the ```initMap```, but later in the analysis the interface invoke is not replaced by the invoke of the implementing class.
Do I need to activate something so Jasmine does that or do I need to implement that myself?

I would greatly appreciate any guiadance.

Cheers!

**Comment by SpringJasmine** [comment]
Thank you very much for your support of Jasmine. During the execution of Jasmine, it will automatically inject the implementation class of the interface where the field is initialized using dependency injection. You can debug the `getIOCObject` method inside the `IOCParser`, mainly checking whether the two places shown in the following figure are normal:

1. The code marked in the **red box** identifies the fields that require dependency injection, such as the `IService` in `AController`. You can add conditions to the breakpoint to determine whether Jasmine has recognized the need for dependency injection for `IService`. 
2. The code marked in the **green box** indicates whether the implementing class corresponding to the Field, such as `ServiceImpl`, has been obtained.

![image](https://github.com/SpringJasmine/Jasmine/assets/89562526/a15dd008-e3c6-4b92-a3c6-fde28a892646)

**Comment by lbettels** [comment]
Thank you for your quick answer.
I checked the points in the program and Jasmine successfully picks up on the needed fields.
```SootField field```

![field1](https://github.com/SpringJasmine/Jasmine/assets/43786637/5f38e124-cfe3-4d4f-b58e-1352f5adefd1)

```SootClass aClass```

![field2](https://github.com/SpringJasmine/Jasmine/assets/43786637/a3d7daa8-6b3d-412e-9673-35bf7695059c)

```realType```

![field3](https://github.com/SpringJasmine/Jasmine/assets/43786637/ca19575e-45bb-46b7-9eed-1ee1014323b3)

Still, after the completion of Jasmine, the active body of the method in question still calls an interface.
The synthetic methods added by Jasmine from the other phases were successfully included in the active body, but the IoC seems to be missing.
![field4](https://github.com/SpringJasmine/Jasmine/assets/43786637/461c1713-ec6f-45b1-a26b-79752de4f42f)

Further help would be greatly appreciated, thank you for taking time to help me with this.

Cheers!

**Comment by SpringJasmine** [comment]
Does the active body of the `<init>` method in `UserRegistrationController` include an instruction to initialize `userService`?

**Comment by lbettels** [comment]
Interestingly this seems to have worked, but i double-checked the method that is invoking the ```IUserService```, and it is not substituted by  ```UserServiceImpl```.

![serviceImpl](https://github.com/SpringJasmine/Jasmine/assets/43786637/79962be1-50ae-4474-8a05-800567868865)

**Comment by SpringJasmine** [comment]
Could you check if the `getUserServiceImpl()` method instantiates the `UserServiceImpl`? If convenient, please post all the active body of the `getUserServiceImpl` method, or check if the set of references for the `iuserservice` variable is empty.

**Comment by lbettels** [comment]
I will look into it tomorrow, as I am on a trip today.
Thank you!

**Comment by lbettels** [comment]
It seems like the method instantiates ```UserServiceImpl```.
Active body of ```getUserServiceImpl()```:

![getUserServiceActiveBody](https://github.com/SpringJasmine/Jasmine/assets/43786637/50d710a6-1cc5-4d7e-b891-f74b590d8e07)

I am unsure as to how to check the references to ```iuserservice```, would you be so kind to explain how to get those?

Cheers!

**Comment by lbettels** [comment]
Hey I just wanted to check if there is any update from your side.
Do you have a suspicion what is going on?
If you could provide me with some guidance again as to where to debug I would be very grateful.
Also please let me know if there is anything i can do to assist you.

Cheers and thank you!

**Comment by SpringJasmine** [comment]
If it's convenient for you, could you send me the entire compiled project where the issue occurred? I'd like to investigate what caused this problem.

**Comment by SpringJasmine** [comment]
I can think of two potential reasons: 
1. The ```<clinit>``` method of ```SingletonFactory``` may be missing a necessary new statement, leading to a failure in instantiation. You might want to examine the IR corresponding to ```SingletonFactory.<clinit>``` method for troubleshooting; 
2. There might not be a call path between the entry point and the method that uses ```IService```. You could check the call path starting from the entry point. 
3. If there's no issue found, then a debug of the Soot process is needed to assess if the ```iuserservice``` pointing object set is empty.

**Comment by lbettels** [comment]
I think I had a misconception of the IoC-Parser.
As far as I can tell, Jasmine is correctly instantiating the fields, but it doesn't try to replace the method calls (which in the bytecode are interface invokes).
I went ahead and am currently modifying Jasmine to go through the methods and replace all units that have interfaceinvoke instructions with virtualinvoke instructions.
The virtualinvoke instructions then point to the classes identified to be the autowired field analysis.

Please correct me if that idea is flawed.
The project I am currently trying to analyze is from this  [Git repository](https://github.com/toyamarodrigo/springboot-invoice-system).

Thank you for your help!

**Comment by SpringJasmine** [comment]
There's no need to replace method calls because the Soot framework automatically manages the invocation between interface methods and their concrete implementations. You can validate this behavior by crafting a simple code sample, opting not to use dependency injection but instead manually initializing fields.

**Comment by lbettels** [comment]
Then I will close the issue now,
thank you so much for helping me better understand your software.
I greatly appreciate you taking time to help me.

Cheers!
